### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by shinnn** [jo/http-image-size#1]
How about supporting https?
This module can support https by simply detecting whether the protocol is https or http.

If you like it, I can create a Pull Request.

**Comment by jo** [comment]
Please!

**Comment by shinnn** [comment]
@jo I'm glad you like it. I created the PR #2.

**Comment by jo** [comment]
Awesome thanks!

**Comment by shinnn** [comment]
Thanks for merging.

And, I wonder if you could add me to the collaborators of this repository.
I can add tests, improve error handling and write detailed readme.

How do you think?

**Comment by jo** [comment]
You're in. Looking forward to your contributions!

**Comment by shinnn** [comment]
Thanks!
